[project]
name = "pyfc"
version = "0.1.0"
description = "Adapter to use IFC files with Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ifcopenshell>=0.8.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.400",
    "pytest>=8.3.5",
    "ruff>=0.11.7",
]
